#%RAML 1.0 NamedExample
userID: '12AW83'
orderID: '2sd8a46f'
orderStatus: 'Processing'
totalCost: '$112'
totalItemsOrdered: 16
lineItems:
  - itemID: 10
    description: Macbook Pro
    noOfItemsOrdered: 10
  - itemID: 20
    description: Gold Coins
    noOfItemsOrdered: 6